import type { NextPage } from 'next'
import 'bootstrap/dist/css/bootstrap.css';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';

const Home: NextPage = () => {

  function imagemHeader() {
    return (
      <>
        <Image src="/favicon.ico" alt="Laboratorio" width={40} height={32} className="me-2" />
        <span className="fs-4">Gobex Exames</span>
      </>
    )
  }

  function linkHeader() {
    return (
      <Link href={"/"} className="d-flex align-items-center text-dark text-decoration-none">
        {imagemHeader()}
      </Link>
    )
  }

  function navHeader() {
    return (
      <div className="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        {linkHeader()}
        <nav className="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <a className="me-3 py-2 text-dark text-decoration-none" href="#divExames">Exames</a>
          <a className="me-3 py-2 text-dark text-decoration-none" href="#divContato">Contato</a>
        </nav>
      </div>
    )
  }

  return (
    <div>
      <Head>
        <title>Gobex Exames</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Leonardo Nascimento Cintra"></meta>

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container py-3">
        <header>

          {navHeader()}


          <div className="pricing-header p-3 pb-md-4 mx-auto text-center">
            <Image className="logo-gobolex" src="/img/gobex.png" width={390} height={230} alt="Gobex Logo" />

            <p className="fs-5 text-muted text-center">O Gobex é um laboratório de exames citológicos que emprega as
              mais modernas
              técnicas na busca por resultados precisos. Isso facilita muito na indicação do tratamento médico
              mais adequado a cada situação específica do paciente.</p>
          </div>
        </header>

        <main>
          <div className="row justify-content-md-center">
            <div className="col-md-auto text-center">

              <h2 className="text-center"> Consulta de exames </h2>
              <br />
              <iframe src="https://worklabweb.com.br/frame.php?Cliente=1687&i=3" name="I1"> </iframe>
            </div>
          </div>
          <br />
          <div id="divExames" className="row row-cols-1 row-cols-md-3 g-4">
            <div className="col">
              <div className="card h-100">
                <Image src="/img/1.png" className="card-img-top" alt="..." width={294} height={294} />
                <div className="card-body">
                  <h5 className="card-title text-center">Teste Nasal COVID-19</h5>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card h-100">
                <Image src="/img/2.png" className="card-img-top" alt="..." width={294} height={294} />
                <div className="card-body">
                  <h5 className="card-title text-center">Hemograma</h5>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card h-100">
                <Image src="/img/3.png" className="card-img-top" alt="..." width={294} height={294} />
                <div className="card-body">
                  <h5 className="card-title text-center">PCR ultrassensivel</h5>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card h-100">
                <Image src="/img/4.png" className="card-img-top" alt="..." width={294} height={294} />
                <div className="card-body">
                  <h5 className="card-title text-center">Ferritina</h5>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card h-100">
                <Image src="/img/5.png" className="card-img-top" alt="..." width={294} height={294} />
                <div className="card-body">
                  <h5 className="card-title text-center">TGO</h5>
                </div>
              </div>
            </div>
            <div className="col">
              <div className="card h-100">
                <Image src="/img/6.png" className="card-img-top" alt="..." width={294} height={294} />
                <div className="card-body">
                  <h5 className="card-title text-center">D&apos; Dímero</h5>
                </div>
              </div>
            </div>
          </div>

          <br />

          <div className="col-12 col-md text-center">
            <div className="card">
              <div id="divContato" className="card-body">
                <h4 className="card-title"><i className="bi bi-chat-fill"></i> Fale conosco!</h4>
                <p className="card-text"><i className="bi bi-telephone-outbound-fill"></i>
                  <b> Fone: </b> (35) 99104-0975
                </p>
                <p className="card-text">
                  <i className="bi bi-geo-alt-fill"></i>
                  <b> Endereço: </b> Avenida São Vicente de Paulo, 230
                  <br /> <b>Bairro:</b> Centro
                  <br /> <b>Cidade:</b> Cássia-MG
                </p>
              </div>
            </div>
          </div>
        </main>

        <footer className="pt-4 my-md-5 pt-md-5 border-top">
          <div className="row">
            <div className="col-12 col-md text-center">
              <Image className="mb-2" src="/favicon.ico" alt="" width={40} height={40} />
              <small className="d-block mb-3 text-muted">&copy; 2021–2022 - Desenvolvido por Leonardo Cintra -
                leonardo.ncintra@outlook.com</small>
            </div>
          </div>
        </footer>
      </div>
    </div>
  )
}

export default Home
